Repository zonemaster/zonemaster-backend, pull requests merged in 2020-11, with the labels that each got.

#663 Remove MySQL and add MariaDB installation instructions
  docs/Installation.md
Labels: A-Installation

#665 Update installation instruction
  docs/Installation.md
Labels: A-Installation, P-High

#666 For release v2020.1 (Backend)
  Changes
  Makefile.PL
  lib/Zonemaster/Backend.pm
Labels: P-High

#668 Updated due to incorrect version number specification (backend)
  Changes
  Makefile.PL
  lib/Zonemaster/Backend.pm
Labels: P-High

#667 Merge develop into master (zonemaster-backend)
  .travis.yml
  Changes
  MANIFEST
  MANIFEST.SKIP
  Makefile.PL
  docs/API.md
  docs/Configuration.md
  docs/Installation.md
  docs/internal-documentation/maintenance/Garbage-Collection-Testing.md
  lib/Zonemaster/Backend.pm
  lib/Zonemaster/Backend/Config.pm
  lib/Zonemaster/Backend/DB.pm
  lib/Zonemaster/Backend/RPCAPI.pm
  lib/Zonemaster/Backend/Translator.pm
  lib/Zonemaster/Backend/Validator.pm
  script/crontab_job_runner/execute_tests.pl
  script/crontab_job_runner/execute_zonemaster_P10.pl
  script/crontab_job_runner/execute_zonemaster_P5.pl
  script/zonemaster_backend_rpcapi.psgi
  script/zonemaster_backend_testagent
  share/backend_config.ini
  share/freebsd-pwd.conf
  share/travis_mysql_backend_config.ini
  share/travis_postgresql_backend_config.ini
  share/travis_sqlite_backend_config.ini
  share/zm-rpcapi.lsb
  share/zm-testagent.lsb
  share/zm_rpcapi-bsd
  share/zmb
  share/zmtest
  t/test01.t
  t/test_DB_backend.pl
Labels: P-High

#671 Resolve issue #670
  t/test01.t
Labels: A-UnitTests, T-Bug

#676 Updates for v2020.1.2 (Backend)
  Changes
  lib/Zonemaster/Backend.pm
Labels: P-High

#678 Merge develop into master (Backend)
  Changes
  lib/Zonemaster/Backend.pm
  t/test01.t
Labels: P-High

#679 Update unit tests (resolve #677)
  t/test01.t
  t/test_validate_syntax.t
Labels: A-UnitTests

#675 Extended zm tools
  share/zmb
  share/zmtest
Labels: A-Code, T-Feature

#672 Remove unused zonemaster_backend_testagent.conf
  MANIFEST
  share/zonemaster_backend_testagent.conf
Labels: A-OSintegration
