Repository zonemaster/zonemaster-backend, pull requests merged in 2020-03, with the labels that each got.

#571 Fixes #570 - UTF-8 issue for idn domain names
  lib/Zonemaster/Backend/DB/PostgreSQL.pm
Labels: A-RCPAPI

#577 Added missing use JSON:PP
  lib/Zonemaster/Backend/DB.pm
Labels: A-Code, S-ProposalExists, T-Bug

#579 Use one service script per daemon on System V
  MANIFEST
  docs/Installation.md
  share/zm-backend.sh
  share/zm-rpcapi.sysv
  share/zm-testagent.sysv
Labels: A-Code

#568 Corrected config documentation
  docs/Configuration.md
  lib/Zonemaster/Backend/Config.pm
Labels: A-Code, A-Documentation, T-Bug
