Repository zonemaster/zonemaster-backend, pull requests merged in 2020-07, with the labels that each got.

#534 Add experimental CLI tools for backend
  MANIFEST.SKIP
  script/zmb
  script/zmtest
Labels: A-Code, P-High

#626 Updates to zmb and zmtest
  MANIFEST
  script/zmtest
  share/zmb
  share/zmtest
Labels: A-Code, S-ProposalExists

#629 Updated language specification handling
  docs/API.md
  docs/Configuration.md
  lib/Zonemaster/Backend/Config.pm
  lib/Zonemaster/Backend/RPCAPI.pm
  lib/Zonemaster/Backend/Translator.pm
  lib/Zonemaster/Backend/Validator.pm
  script/zonemaster_backend_rpcapi.psgi
  share/backend_config.ini
  share/travis_mysql_backend_config.ini
  share/travis_postgresql_backend_config.ini
  share/travis_sqlite_backend_config.ini
  t/test01.t
  t/test_DB_backend.pl
Labels: A-Code, A-Documentation, A-RCPAPI, A-Translation, A-UnitTests, S-ProposalExists

#625 Removed unused GEOLOCATION
  docs/Configuration.md
  share/backend_config.ini
Labels: A-Documentation
