Repository zonemaster/zonemaster-backend, pull requests merged in 2020-09, with the labels that each got.

#634 Fix failing test
  lib/Zonemaster/Backend/RPCAPI.pm
  t/test_DB_backend.pl
Labels: A-Travis

#633 Install binary package for Try::Tiny on Debian/Ubuntu
  .travis.yml
  Makefile.PL
  docs/Installation.md
Labels: A-Installation

#632 Language option for zmtest
  share/zmb
  share/zmtest
Labels: A-Code

#641 Remove direct dependency on Net::IP::XS
  Makefile.PL
  docs/Installation.md
  lib/Zonemaster/Backend/RPCAPI.pm
Labels: A-Code

#639 Deploy without debug middleware
  script/zonemaster_backend_rpcapi.psgi
Labels: P-High

#642 Remove unused scripts and dependencies
  MANIFEST
  Makefile.PL
  docs/Installation.md
  script/crontab_job_runner/execute_tests.pl
  script/crontab_job_runner/execute_zonemaster_P10.pl
  script/crontab_job_runner/execute_zonemaster_P5.pl
Labels: A-BuildSystem, A-Code, P-High

#643 Activate Norwegian in Backend
  docs/API.md
  docs/Configuration.md
  docs/Installation.md
  share/backend_config.ini
  share/travis_mysql_backend_config.ini
  share/travis_postgresql_backend_config.ini
  share/travis_sqlite_backend_config.ini
Labels: A-Translation, A-Travis, P-High

#645 Update Travis config
  .travis.yml
Labels: A-Travis, P-High
