Repository zonemaster/zonemaster-backend, pull requests merged in 2020-10, with the labels that each got.

#652 Fix broken zmtest --lang option
  share/zmtest
Labels: A-Code

#650 Attach adapter to Log::Any in RPCAPI
  script/zonemaster_backend_rpcapi.psgi
Labels: A-Logging

#649 Fix warning in RPCAPI
  lib/Zonemaster/Backend/Translator.pm
Labels: A-Translation

#655 Clean up Zonemaster::Backend::Translator::translate_tag
  lib/Zonemaster/Backend/RPCAPI.pm
  lib/Zonemaster/Backend/Translator.pm
Labels: A-Translation

#648 Fix API documentation
  docs/API.md
Labels: A-Documentation

#656 Add log level setting to RPCAPI start script
  share/zm-rpcapi.lsb
  share/zm_rpcapi-bsd
Labels: A-OSintegration

#545 Fixes issue #213 - Internal error details are leaked
  lib/Zonemaster/Backend/RPCAPI.pm
Labels: A-Code, P-High

#658 Updated smoke test
  docs/Installation.md
  share/zmtest
Labels: A-Code

#660 Fixes in documentation
  docs/Installation.md
Labels: A-Documentation
