Repository zonemaster/zonemaster-backend, pull requests merged in 2021-11, with the labels that each got.

#897 Adds missing file to MANIFEST
  MANIFEST
Labels: T-Bug

#899 Adds PO file for translation to Swedish
  share/sv.po
Labels: A-Translation

#898 Create and update PO files
  share/da.po
  share/es.po
  share/fi.po
  share/fr.po
  share/nb.po
Labels: A-Translation

#902 Update dependencies
  Makefile.PL
  docs/Installation.md
  docs/upgrade/upgrade_zonemaster_backend_ver_8.0.0.md
Labels: T-Bug

#906 Fix MySQL cleanup
  docs/Installation.md
  share/cleanup-mysql.sql
Labels: T-Bug

#908 Update Rocky installation instruction
  docs/Installation.md
Labels: P-High, A-Documentation

#918 Add MO files to manifest
  MANIFEST
Labels: P-High, A-Translation
