Repository zonemaster/zonemaster-backend, pull requests merged in 2021-03, with the labels that each got.

#713 Fixes correct start order at start-up
  share/zm_testagent-bsd
Labels: A-OSintegration, T-Bug

#692 Make age for reused test configurable
  docs/Configuration.md
  lib/Zonemaster/Backend/Config.pm
  lib/Zonemaster/Backend/RPCAPI.pm
  share/backend_config.ini
Labels: A-Code, T-Feature

#721 Clean up commented out code
  lib/Zonemaster/Backend/DB/PostgreSQL.pm
Labels: A-Code

#720 Fix unitialized value
  lib/Zonemaster/Backend/Config.pm
Labels: A-Code, T-Bug

#723 Properly initialize SQLite handle
  lib/Zonemaster/Backend/DB/SQLite.pm
Labels: A-Databases

#715 SQLite: harmonize get_test_history with MySQL and PostgreSQL
  lib/Zonemaster/Backend/DB/SQLite.pm
Labels: A-Databases

#726 Remove configuration that allows non-hash test ID
  docs/Configuration.md
  lib/Zonemaster/Backend/Config.pm
  lib/Zonemaster/Backend/DB.pm
  lib/Zonemaster/Backend/DB/MySQL.pm
  lib/Zonemaster/Backend/DB/PostgreSQL.pm
  lib/Zonemaster/Backend/DB/SQLite.pm
  share/travis_mysql_backend_config.ini
  share/travis_postgresql_backend_config.ini
  t/test_DB_backend.pl
Labels: A-Databases, A-Documentation, A-Travis

#727 Require test ID to be 16 character "hash_id" in all input
  docs/API.md
  lib/Zonemaster/Backend/Validator.pm
Labels: A-RCPAPI
