Repository zonemaster/zonemaster-backend, pull requests merged in 2021-12, with the labels that each got.

#921 Adds Finnish translation of error messages
  share/fi.po
Labels: A-Translation

#924 Preparation for release v2021.2 (Backend)
  Changes
  Makefile.PL
  lib/Zonemaster/Backend.pm
Labels: P-High

#935 First draft of Norwegian translation
  share/nb.po
Labels: A-Translation

#930 Add danish translation
  share/da.po
Labels: A-Translation

#932 Fix internationalized testing failure with error: "malformed UTF-8 character in JSON string"
  lib/Zonemaster/Backend/DB.pm
Labels: T-Bug, P-High

#928 Fix inconsistency in SQLite test's age
  lib/Zonemaster/Backend/DB/SQLite.pm
Labels: T-Bug

#929 improve code quality
  lib/Zonemaster/Backend/Metrics.pm
Labels: T-Bug

#936 First translation to spanish language
  share/es.po
Labels: A-Translation

#926 Updated instruction for FreeBSD due to updated indirect dependencies
  docs/Installation.md
Labels: T-Bug

#900 Adds Spanish language (es_ES) to various places
  docs/API.md
  docs/Configuration.md
  docs/Installation.md
  share/backend_config.ini
  share/travis_mysql_backend_config.ini
  share/travis_postgresql_backend_config.ini
  share/travis_sqlite_backend_config.ini
Labels: P-High, A-Translation

#939 Update Upgrade.md for the release
  docs/Upgrade.md
Labels: A-Documentation

#940 Preparation for v2021.2.1 release (Backend)
  Changes
  Makefile.PL
  lib/Zonemaster/Backend.pm
Labels: P-High
