Repository zonemaster/zonemaster-backend, pull requests merged in 2021-04, with the labels that each got.

#717 Load ini file at RPCAPI and TestAgent startup only
  docs/Configuration.md
  lib/Zonemaster/Backend/Config.pm
  lib/Zonemaster/Backend/RPCAPI.pm
  lib/Zonemaster/Backend/TestAgent.pm
  script/zonemaster_backend_rpcapi.psgi
  script/zonemaster_backend_testagent
  t/test01.t
  t/test_DB_backend.pl
  t/test_validate_syntax.t
Labels: A-RCPAPI, A-TestAgent

#732 SQLite: keep creation_time in UTC in test_results
  lib/Zonemaster/Backend/DB/SQLite.pm
Labels: T-Bug

#725 Fix logical type errors
  lib/Zonemaster/Backend/RPCAPI.pm
  t/test_validate_syntax.t
Labels: A-RCPAPI

#712 Adds fi_FI to supported languages in RPCAPI
  docs/API.md
  docs/Configuration.md
  docs/Installation.md
  share/backend_config.ini
  share/travis_mysql_backend_config.ini
  share/travis_postgresql_backend_config.ini
  share/travis_sqlite_backend_config.ini
Labels: A-Translation

#734 RPCAPI catch error on missing params object
  lib/Zonemaster/Backend/RPCAPI.pm
Labels: A-RCPAPI

#730 Separate config section for each db engine
  docs/Configuration.md
  docs/Installation.md
  lib/Zonemaster/Backend/Config.pm
  lib/Zonemaster/Backend/DB/MySQL.pm
  lib/Zonemaster/Backend/DB/PostgreSQL.pm
  lib/Zonemaster/Backend/DB/SQLite.pm
  script/create_db_mysql.pl
  script/create_db_postgresql_9.3.pl
  script/zonemaster_backend_rpcapi.psgi
  share/backend_config.ini
  share/create_db_sqlite.pl
  share/patch_mysql_db_zonemaster_backend_ver_1.0.3.pl
  share/patch_mysql_db_zonemaster_backend_ver_5.0.0.pl
  share/patch_mysql_db_zonemaster_backend_ver_5.0.2.pl
  share/patch_postgresql_db_zonemaster_backend_ver_1.0.3.pl
  share/patch_postgresql_db_zonemaster_backend_ver_5.0.0.pl
  share/travis_mysql_backend_config.ini
  share/travis_postgresql_backend_config.ini
  share/travis_sqlite_backend_config.ini
  share/zm-rpcapi.lsb
  share/zm-testagent.lsb
  share/zm_rpcapi-bsd
  share/zm_testagent-bsd
Labels: A-Databases

#739 Remove old CodeSnippets
  CodeSnippets/Client.pm
  CodeSnippets/client.pl
  CodeSnippets/sample_api_call__get_data_from_parent_zone.pl
  CodeSnippets/sample_api_call__get_ns_ips.pl
  CodeSnippets/sample_api_call__validate_syntax.pl
  CodeSnippets/sample_api_call__version_info.pl
Labels: A-Code

#745 Parse config
  .travis.yml
  Makefile.PL
  docs/Installation.md
  lib/Zonemaster/Backend/Config.pm
  lib/Zonemaster/Backend/RPCAPI.pm
  share/travis_postgresql_backend_config.ini
  t/config.t
Labels: FA-Backend-conf

#749 Uniform config property getter methods
  docs/Configuration.md
  lib/Zonemaster/Backend/Config.pm
  t/config.t
  t/test_validate_syntax.t
Labels: FA-Backend-conf

#754 Document keys number_of_processes_for_{frontend,batch}_testing
  docs/Configuration.md
Labels: A-Documentation
