Repository zonemaster/zonemaster-backend, pull requests merged in 2021-07, with the labels that each got.

#810 Corrects zmb
  script/zmb
Labels: T-Bug

#811 Fix translation
  lib/Zonemaster/Backend/RPCAPI.pm
  lib/Zonemaster/Backend/Translator.pm
Labels: T-Bug

#816 Clarifies profiles in the documentation
  docs/API.md
  docs/Configuration.md
Labels: A-Documentation

#814 Corrects the description of the reuse time
  docs/API.md
Labels: A-Documentation, T-Bug

#826 Correct the handling of delegated and undelegated in historic tests
  MANIFEST
  README.md
  docs/API.md
  docs/upgrade_db_zonemaster_backend_ver_7.0.0.md
  lib/Zonemaster/Backend/DB.pm
  lib/Zonemaster/Backend/DB/MySQL.pm
  lib/Zonemaster/Backend/DB/PostgreSQL.pm
  lib/Zonemaster/Backend/DB/SQLite.pm
  script/create_db_postgresql_9.3.pl
  share/initial-mysql.sql
  share/initial-postgres.sql
  share/patch_postgresql_db_zonemaster_backend_ver_7.0.0.pl
  t/test01.data
  t/test01.t
Labels: T-Bug

#824 Update severity
  docs/API.md
  lib/Zonemaster/Backend/DB/MySQL.pm
  lib/Zonemaster/Backend/DB/SQLite.pm
Labels: T-Bug

#822 Add table of contents to API and Configuration documents
  docs/API.md
  docs/Configuration.md
Labels: A-Documentation
