Repository zonemaster/zonemaster-backend, pull requests merged in 2021-01, with the labels that each got.

#688 Remove unused configuration properties
  lib/Zonemaster/Backend/Config.pm
  share/backend_config.ini
  share/travis_mysql_backend_config.ini
  share/travis_postgresql_backend_config.ini
  share/travis_sqlite_backend_config.ini
Labels: A-Code

#690 Updated sqlite solution
  MANIFEST
  lib/Zonemaster/Backend/DB/MySQL.pm
  lib/Zonemaster/Backend/DB/SQLite.pm
  lib/Zonemaster/Backend/RPCAPI.pm
  script/add-batch-job.pl
  script/add-test.pl
  share/create_db_sqlite.pl
  t/test01.t
Labels: A-Databases, P-High, T-Feature

#694 Deprecate force_hash_id_use_in_API_starting_from_id
  docs/Configuration.md
Labels: A-Documentation

#693 Proper installation of zmtest and zmb
  MANIFEST
  MANIFEST.SKIP
  Makefile.PL
  docs/Installation.md
  script/zmb
  script/zmtest
Labels: A-Code

#695 Installation instruction for SQLite
  docs/Installation.md
Labels: A-Databases, A-Installation, P-High

#696 Update CentOS installation instruction
  docs/Installation.md
Labels: A-Installation, P-High

#698 Make Backend start automatically when booting
  docs/Installation.md
Labels: A-Installation, P-High

#699 Corrects Installation instruction for FreeBSD
  docs/Installation.md
Labels: A-Installation, P-High

#700 Update Debian installation instructions
  docs/Installation.md
Labels: A-Documentation, P-High

#701 Update SQLite note
  docs/Installation.md
Labels: A-Documentation
