Repository zonemaster/zonemaster-backend, pull requests merged in 2021-09, with the labels that each got.

#855 Update documentation to use SQLite by default
  docs/Installation.md
  share/backend_config.ini
Labels: A-Documentation

#862 Backport #851 (Load config only once)
  share/zm-rpcapi.lsb
  share/zm_rpcapi-bsd
Labels: T-Bug, P-High

#850 Backport fix user api
  Changes
  Makefile.PL
  docs/Configuration.md
  docs/Installation.md
  lib/Zonemaster/Backend/Config.pm
  lib/Zonemaster/Backend/Validator.pm
  script/zonemaster_backend_rpcapi.psgi
  share/backend_config.ini
Labels: P-High

#863 Preparation for release v2021.1.3
  Changes
  lib/Zonemaster/Backend.pm
Labels: P-High

#867 Merge fix-release-v2021.1.3 into master (Backend)
  Changes
  Makefile.PL
  docs/Configuration.md
  docs/Installation.md
  lib/Zonemaster/Backend.pm
  lib/Zonemaster/Backend/Config.pm
  lib/Zonemaster/Backend/Validator.pm
  script/zonemaster_backend_rpcapi.psgi
  share/backend_config.ini
  share/zm-rpcapi.lsb
  share/zm_rpcapi-bsd
Labels: P-High

#871 Change link from http to https
  docs/API.md
Labels: A-Documentation

#839 use plack reverse proxy middleware to get real remote ip
  Makefile.PL
  docs/Configuration.md
  docs/Installation.md
  lib/Zonemaster/Backend/Config.pm
  lib/Zonemaster/Backend/Validator.pm
  script/zonemaster_backend_rpcapi.psgi
  share/backend_config.ini
Labels: P-High

#870 Updates Changes and Backend.pm with updates for release v2021.1.3 (Backend)
  Changes
  lib/Zonemaster/Backend.pm
Labels: P-High

#873 Adds missing information in API document
  docs/API.md
  docs/Configuration.md
Labels: A-Documentation
