Repository zonemaster/zonemaster-backend, pull requests merged in 2022-05, with the labels that each got.

#986 Update IDN support warning message
  lib/Zonemaster/Backend/TestAgent.pm
  share/fr.po
Labels: A-Translation

#1005 Normalize domain column
  lib/Zonemaster/Backend/DB.pm
  lib/Zonemaster/Backend/DB/MySQL.pm
  lib/Zonemaster/Backend/DB/PostgreSQL.pm
  lib/Zonemaster/Backend/DB/SQLite.pm
  share/patch/patch_db_zonemaster_backend_ver_8.2.0.pl
  t/batches.t
  t/test01.t
Labels: T-Bug

#1004 fix initialization of logger when level variable is undef
  lib/Zonemaster/Backend/Log.pm
  script/zonemaster_backend_rpcapi.psgi
Labels: T-Bug

#1014 Fix log output
  lib/Zonemaster/Backend/Log.pm
Labels: T-Bug

#1023 Installation on Rocky
  docs/Installation.md
  t/lifecycle.t
Labels: P-High

#1025 Update spanish translation file for upcoming release, ticket #1018
  share/es.po
Labels: P-High, A-Translation
