Repository zonemaster/zonemaster-backend, pull requests merged in 2022-11, with the labels that each got.

#1055 Add testcase results
  docs/API.md
  lib/Zonemaster/Backend/RPCAPI.pm
  lib/Zonemaster/Backend/Translator.pm
Labels: V-Minor

#1057 Fix recursor init
  script/zonemaster_backend_rpcapi.psgi
Labels: T-Bug, V-Patch

#1058 Provide human readable messages for backend messages
  lib/Zonemaster/Backend/RPCAPI.pm
  lib/Zonemaster/Backend/Translator.pm
Labels: P-High, V-Minor

#1059 Corrects the license statement in Backend.pm
  README.md
  lib/Zonemaster/Backend.pm
Labels: A-Documentation, V-Patch
