Repository zonemaster/zonemaster-backend, pull requests merged in 2022-12, with the labels that each got.

#1067 Updates deprecation information
  docs/API.md
  docs/Configuration.md
Labels: A-Documentation, V-Patch

#1066 Fix zmtest script
  script/zmtest
Labels: T-Bug, V-Patch

#1069 Update dependencies for Rocky 8.7
  docs/Installation.md
Labels: A-Documentation, V-Patch

#1068 Updates for release v2022.2 (Backend)
  Changes
  Makefile.PL
  lib/Zonemaster/Backend.pm
Labels: P-High

#1070 Merge develop into master (Backend)
  .travis.yml
  Changes
  Makefile.PL
  README.md
  docs/API.md
  docs/Configuration.md
  docs/Installation.md
  lib/Zonemaster/Backend.pm
  lib/Zonemaster/Backend/DB.pm
  lib/Zonemaster/Backend/RPCAPI.pm
  lib/Zonemaster/Backend/Translator.pm
  lib/Zonemaster/Backend/Validator.pm
  script/zmtest
  script/zonemaster_backend_rpcapi.psgi
  t/test01.t
  t/test_profile.json
Labels: P-High
