Repository zonemaster/zonemaster-backend, pull requests merged in 2022-07, with the labels that each got.

#1034 Update danish translation
  share/da.po
Labels: P-High, A-Translation

#1046 Respect net.ipv4 and net.ipv6
  lib/Zonemaster/Backend/Config.pm
  lib/Zonemaster/Backend/DB.pm
  lib/Zonemaster/Backend/RPCAPI.pm
  lib/Zonemaster/Backend/TestAgent.pm
  t/db.t
Labels: T-Bug, P-High

#1047 Merge develop into master (Backend)
  Changes
  Makefile.PL
  lib/Zonemaster/Backend.pm
  lib/Zonemaster/Backend/Config.pm
  lib/Zonemaster/Backend/DB.pm
  lib/Zonemaster/Backend/RPCAPI.pm
  lib/Zonemaster/Backend/TestAgent.pm
  share/da.po
  t/db.t
Labels: P-High
