Repository zonemaster/zonemaster-backend, pull requests merged in 2023-01, with the labels that each got.

#1072 Fix uninitialized value warning in zm-rpcapi.log
  lib/Zonemaster/Backend/RPCAPI.pm
Labels: T-Bug

#1074 Update French translation
  share/fr.po
Labels: A-Translation, V-Patch

#1073 Update the Swedish translation (Backend)
  share/sv.po
Labels: A-Translation, V-Patch

#1075 Updates for release v2022.2.1 (Backend)
  Changes
  Makefile.PL
  lib/Zonemaster/Backend.pm
Labels: P-High

#1076 Merge develop into master (Backend)
  Changes
  Makefile.PL
  lib/Zonemaster/Backend.pm
  lib/Zonemaster/Backend/RPCAPI.pm
  share/fr.po
  share/sv.po
Labels: P-High
