Repository zonemaster/zonemaster-backend, pull requests merged in 2023-02, with the labels that each got.

#1081 Remove deprecated "creation_time" key
  docs/API.md
  lib/Zonemaster/Backend/DB.pm
  lib/Zonemaster/Backend/DB/PostgreSQL.pm
  t/batches.t
  t/test01.t
Labels: V-Major

#1080 Provide a rule "new-po" to create an empty PO file
  share/GNUmakefile
Labels: V-Patch

#1054 Always return an object from API methods and deprecate all existing API methods
  docs/API.md
  docs/Configuration.md
  lib/Zonemaster/Backend/Config.pm
  lib/Zonemaster/Backend/RPCAPI.pm
  script/zonemaster_backend_rpcapi.psgi
Labels: V-Minor

#1079 Updates translations (Backend)
  share/es.po
  share/fi.po
  share/nb.po
Labels: A-Translation, V-Patch
