Repository zonemaster/zonemaster-backend, pull requests merged in 2023-05, with the labels that each got.

#1098 Fix broken test
  t/test01.t
Labels: T-Bug, V-Patch

#1097 Remove deprecated features related to locale
  docs/API.md
  docs/Configuration.md
  lib/Zonemaster/Backend/Config.pm
  lib/Zonemaster/Backend/RPCAPI.pm
  lib/Zonemaster/Backend/Validator.pm
  t/config.t
  t/test01.t
  t/test_validate_syntax.t
Labels: V-Major

#1096 Fix wrong schema for deprecated method
  lib/Zonemaster/Backend/RPCAPI.pm
Labels: T-Bug, V-Patch

#1102 Update French translations for release 2023.1
  share/fr.po
Labels: A-Translation, V-Patch

#1104 Remove documentation (moved to zonemaster/zonemaster)
  MANIFEST
  README.md
  docs/API.md
  docs/Architecture.md
  docs/Configuration.md
  docs/EnvironmentVariables.md
  docs/GettingStarted.md
  docs/Installation.md
  docs/Telemetry.md
  docs/TypographicConventions.md
  docs/Upgrade.md
  docs/upgrade/upgrade_zonemaster_backend_ver_1.0.3.md
  docs/upgrade/upgrade_zonemaster_backend_ver_1.1.0.md
  docs/upgrade/upgrade_zonemaster_backend_ver_5.0.0.md
  docs/upgrade/upgrade_zonemaster_backend_ver_5.0.2.md
  docs/upgrade/upgrade_zonemaster_backend_ver_8.0.0.md
  docs/upgrade/upgrade_zonemaster_backend_ver_9.0.0.md
  lib/Zonemaster/Backend/Config.pm
  lib/Zonemaster/Backend/DB.pm
  lib/Zonemaster/Backend/Validator.pm
  share/backend_config.ini
  share/patch/README.txt
Labels: A-Documentation

#1103 Update translations (Backend)
  share/da.po
  share/es.po
  share/fi.po
  share/nb.po
  share/sv.po
Labels: A-Translation, V-Patch

#1106 Clean up
  .gitignore
  MANIFEST.SKIP
  Makefile.PL
Labels: V-Patch
