Repository zonemaster/zonemaster-backend, pull requests merged in 2025-06, with the labels that each got.

#1212 Sort historic tests by creation date and not ID
  lib/Zonemaster/Backend/DB.pm
Labels: T-Bug

#1143 Adapt to changed Engine API
  lib/Zonemaster/Backend/DB.pm
  lib/Zonemaster/Backend/RPCAPI.pm
  lib/Zonemaster/Backend/Validator.pm
Labels: V-Patch

#1215 Redefines batch_status to replace get_batch_job_result
  lib/Zonemaster/Backend/DB.pm
  lib/Zonemaster/Backend/RPCAPI.pm
  script/zmb
  script/zonemaster_backend_rpcapi.psgi
  t/batches.t
Labels: V-Minor

#1213 Norwegian translation update 2025-04
  share/nb.po
Labels: A-Translation, V-Patch
